last_change = 2025-03-14T23:09:26.295480Z
addr = 0x580
size = 0x2a
name = "new_start"
artifact_type = "Function"

[header]
last_change = 2025-03-14T23:09:26.295480Z
name = "new_start"
addr = 0x580

[header.args]
