last_change = 2025-03-14T22:22:20.877307Z
addr = 0x71d
size = 0xb8
name = "main"
artifact_type = "Function"

[header]
last_change = 2025-03-14T22:22:20.877307Z
name = "main"
addr = 0x71d

[header.args]

[stack_vars.-0x18]
offset = -24
name = "things"
size = 0x10
addr = 0x71d

[stack_vars.-0x2c]
offset = -44
name = "your_mom"
size = 0x4
addr = 0x71d
