last_change = 2025-02-11T23:11:32.981983Z
addr = 0x71d
size = 0xb8
name = "my_main"
artifact_type = "Function"

[header]
last_change = 2025-02-11T23:11:32.981983Z
name = "my_main"
addr = 0x71d

[header.args]

[stack_vars.-0x18]
last_change = 2025-02-02T05:27:54.960623Z
offset = -24
name = "things"
size = 0x10
addr = 0x71d

[stack_vars.-0x2c]
last_change = 2025-02-02T05:27:57.590030Z
offset = -44
name = "your_mom"
size = 0x4
addr = 0x71d
